vim.o.number         = true
vim.o.relativenumber = true
vim.o.clipboard      = "unnamed"
vim.o.termguicolors  = false
vim.o.background     = 'dark'
vim.o.tabstop        = 2
vim.o.smarttab       = true
vim.o.scrolloff      = 6
vim.o.ignorecase     = true
vim.o.smartcase      = true
vim.o.encoding       = 'UTF-8'
vim.o.splitright     = true
vim.o.splitbelow     = true
vim.o.foldenable     = true
vim.o.foldnestmax    = 10
vim.o.foldlevel      = 99
vim.o.foldmethod   = "indent"

-- vim.env.NVIM_TUI_ENABLE_TRUE_COLOR = 1

-- vim.o.ttyfast = true
-- vim.o.autochdir = true
-- vim.o.exrc = true
-- vim.o.secure = false
-- vim.o.number = true
-- vim.o.relativenumber = true
-- vim.o.cursorline = true
-- vim.o.expandtab = false
-- vim.o.tabstop = 2
-- vim.o.smarttab = true
-- vim.o.shiftwidth = 2
-- vim.o.softtabstop = 2
-- vim.o.autoindent = true
-- vim.o.list = true
-- vim.o.listchars = 'tab:|\\ ,trail:▫'
-- vim.o.scrolloff = 6
-- vim.o.foldmethod = 'indent'
-- vim.o.timeout = false
-- vim.o.viewoptions = 'cursor,folds,slash,unix'
-- vim.o.wrap = true
-- vim.o.textwidth = 0
-- vim.o.indentexpr = ''
-- vim.o.inccommand = 'split'
-- vim.o.ignorecase = true
-- vim.o.smartcase = true
-- vim.o.shortmess = vim.o.shortmess .. 'c'
-- vim.o.completeopt = 'longest,noinsert,menuone,noselect,preview'
-- vim.o.completeopt = 'menuone,noinsert,noselect,preview'
-- -- vim.o.lazyredraw = true
-- vim.o.visualbell = true
-- vim.o.colorcolumn = '100'
-- vim.o.updatetime = 100
-- vim.o.virtualedit = 'block'
